=== jacksonfelipe/L2JPremium-High-Five-/world/config/config.dtd
<!ELEMENT AllowedCommands ANY>
<!ATTLIST AllowedCommands
  set CDATA #IMPLIED
>
<!ELEMENT BanChatBonusCount ANY>
<!ATTLIST BanChatBonusCount
  set CDATA #IMPLIED
>
<!ELEMENT BanChatBonusId ANY>
<!ATTLIST BanChatBonusId
  set CDATA #IMPLIED
>
<!ELEMENT BanChatCountPerDay ANY>
<!ATTLIST BanChatCountPerDay
  set CDATA #IMPLIED
>
<!ELEMENT BanChatDelay ANY>
<!ATTLIST BanChatDelay
  set CDATA #IMPLIED
>
<!ELEMENT BanChatMaxValue ANY>
<!ATTLIST BanChatMaxValue
  set CDATA #IMPLIED
>
<!ELEMENT BlockInventory ANY>
<!ATTLIST BlockInventory
  set CDATA #IMPLIED
>
<!ELEMENT CanAnnounce ANY>
<!ATTLIST CanAnnounce
  set CDATA #IMPLIED
>
<!ELEMENT CanAttack ANY>
<!ATTLIST CanAttack
  set CDATA #IMPLIED
>
<!ELEMENT CanBan ANY>
<!ATTLIST CanBan
  set CDATA #IMPLIED
>
<!ELEMENT CanBanChat ANY>
<!ATTLIST CanBanChat
  set CDATA #IMPLIED
>
<!ELEMENT CanChangeClass ANY>
<!ATTLIST CanChangeClass
  set CDATA #IMPLIED
>
<!ELEMENT CanChatPenalty ANY>
<!ATTLIST CanChatPenalty
  set CDATA #IMPLIED
>
<!ELEMENT CanDelete ANY>
<!ATTLIST CanDelete
  set CDATA #IMPLIED
>
<!ELEMENT CanEditChar ANY>
<!ATTLIST CanEditChar
  set CDATA #IMPLIED
>
<!ELEMENT CanEditCharAll ANY>
<!ATTLIST CanEditCharAll
  set CDATA #IMPLIED
>
<!ELEMENT CanEditNPC ANY>
<!ATTLIST CanEditNPC
  set CDATA #IMPLIED
>
<!ELEMENT CanEditPledge ANY>
<!ATTLIST CanEditPledge
  set CDATA #IMPLIED
>
<!ELEMENT CanEvaluate ANY>
<!ATTLIST CanEvaluate
  set CDATA #IMPLIED
>
<!ELEMENT CanGmEdit ANY>
<!ATTLIST CanGmEdit
  set CDATA #IMPLIED
>
<!ELEMENT CanJail ANY>
<!ATTLIST CanJail
  set CDATA #IMPLIED
>
<!ELEMENT CanJoinClan ANY>
<!ATTLIST CanJoinClan
  set CDATA #IMPLIED
>
<!ELEMENT CanJoinParty ANY>
<!ATTLIST CanJoinParty
  set CDATA #IMPLIED
>
<!ELEMENT CanKick ANY>
<!ATTLIST CanKick
  set CDATA #IMPLIED
>
<!ELEMENT CanPolymorph ANY>
<!ATTLIST CanPolymorph
  set CDATA #IMPLIED
>
<!ELEMENT CanReload ANY>
<!ATTLIST CanReload
  set CDATA #IMPLIED
>
<!ELEMENT CanRename ANY>
<!ATTLIST CanRename
  set CDATA #IMPLIED
>
<!ELEMENT CanRestart ANY>
<!ATTLIST CanRestart
  set CDATA #IMPLIED
>
<!ELEMENT CanTeleport ANY>
<!ATTLIST CanTeleport
  set CDATA #IMPLIED
>
<!ELEMENT CanUnBanChat ANY>
<!ATTLIST CanUnBanChat
  set CDATA #IMPLIED
>
<!ELEMENT CanUseGMCommand ANY>
<!ATTLIST CanUseGMCommand
  set CDATA #IMPLIED
>
<!ELEMENT CanViewChar ANY>
<!ATTLIST CanViewChar
  set CDATA #IMPLIED
>
<!ELEMENT CanViewNPC ANY>
<!ATTLIST CanViewNPC
  set CDATA #IMPLIED
>
<!ELEMENT Door ANY>
<!ATTLIST Door
  set CDATA #IMPLIED
>
<!ELEMENT FastUnstuck ANY>
<!ATTLIST FastUnstuck
  set CDATA #IMPLIED
>
<!ELEMENT GodMode ANY>
<!ATTLIST GodMode
  set CDATA #IMPLIED
>
<!ELEMENT Heal ANY>
<!ATTLIST Heal
  set CDATA #IMPLIED
>
<!ELEMENT IsEventGm ANY>
<!ATTLIST IsEventGm
  set CDATA #IMPLIED
>
<!ELEMENT IsGM ANY>
<!ATTLIST IsGM
  set CDATA #IMPLIED
>
<!ELEMENT Menu ANY>
<!ATTLIST Menu
  set CDATA #IMPLIED
>
<!ELEMENT MonsterRace ANY>
<!ATTLIST MonsterRace
  set CDATA #IMPLIED
>
<!ELEMENT PeaceAttack ANY>
<!ATTLIST PeaceAttack
  set CDATA #IMPLIED
>
<!ELEMENT PlayerID ANY>
<!ATTLIST PlayerID
  set CDATA #IMPLIED
>
<!ELEMENT Res ANY>
<!ATTLIST Res
  set CDATA #IMPLIED
>
<!ELEMENT ResurectFixed ANY>
<!ATTLIST ResurectFixed
  set CDATA #IMPLIED
>
<!ELEMENT Rider ANY>
<!ATTLIST Rider
  set CDATA #IMPLIED
>
<!ELEMENT Unblock ANY>
<!ATTLIST Unblock
  set CDATA #IMPLIED
>
<!ELEMENT UseGMShop ANY>
<!ATTLIST UseGMShop
  set CDATA #IMPLIED
>
<!ELEMENT UseInventory ANY>
<!ATTLIST UseInventory
  set CDATA #IMPLIED
>
<!ELEMENT UseShop ANY>
<!ATTLIST UseShop
  set CDATA #IMPLIED
>
<!ELEMENT UseTrade ANY>
<!ATTLIST UseTrade
  set CDATA #IMPLIED
>
<!ELEMENT UseWarehouse ANY>
<!ATTLIST UseWarehouse
  set CDATA #IMPLIED
>
<!ELEMENT achievement ANY>
<!ATTLIST achievement
  cat CDATA #IMPLIED
  desc CDATA #IMPLIED
  id CDATA #IMPLIED
  type CDATA #IMPLIED
>
<!ELEMENT api ANY>
<!ATTLIST api
  id CDATA #IMPLIED
  key CDATA #IMPLIED
  zone CDATA #IMPLIED
>
<!ELEMENT appender ANY>
<!ATTLIST appender
  class CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT appender-ref ANY>
<!ATTLIST appender-ref
  ref CDATA #IMPLIED
>
<!ELEMENT aug ANY>
<!ATTLIST aug
  desc CDATA #IMPLIED
  id CDATA #IMPLIED
  itemCount CDATA #IMPLIED
  itemId CDATA #IMPLIED
  skillId CDATA #IMPLIED
  skillLvl CDATA #IMPLIED
  statsId CDATA #IMPLIED
  type CDATA #IMPLIED
>
<!ELEMENT cache ANY>
<!ATTLIST cache
  eternal CDATA #IMPLIED
  maxElementsInMemory CDATA #IMPLIED
  memoryStoreEvictionPolicy CDATA #IMPLIED
  name CDATA #IMPLIED
  overflowToDisk CDATA #IMPLIED
  statistics CDATA #IMPLIED
  timeToIdleSeconds CDATA #IMPLIED
  timeToLiveSeconds CDATA #IMPLIED
>
<!ELEMENT cat ANY>
<!ATTLIST cat
  desc CDATA #IMPLIED
  icon CDATA #IMPLIED
  id CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT categories ANY>
<!ELEMENT category ANY>
<!ATTLIST category
  chance CDATA #IMPLIED
>
<!ELEMENT char ANY>
<!ELEMENT class ANY>
<!ATTLIST class
  id CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT classes ANY>
<!ELEMENT config ANY>
<!ATTLIST config
  enableVoteReward CDATA #IMPLIED
>
<!ELEMENT defaultCache ANY>
<!ATTLIST defaultCache
  diskExpiryThreadIntervalSeconds CDATA #IMPLIED
  diskPersistent CDATA #IMPLIED
  eternal CDATA #IMPLIED
  maxElementsInMemory CDATA #IMPLIED
  overflowToDisk CDATA #IMPLIED
  timeToIdleSeconds CDATA #IMPLIED
  timeToLiveSeconds CDATA #IMPLIED
>
<!ELEMENT diskStore ANY>
<!ATTLIST diskStore
  path CDATA #IMPLIED
>
<!ELEMENT display ANY>
<!ATTLIST display
  description CDATA #IMPLIED
  enabled CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT ehcache ANY>
<!ATTLIST ehcache
  monitoring CDATA #IMPLIED
  updateCheck CDATA #IMPLIED
  noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT group ANY>
<!ATTLIST group
  chance CDATA #IMPLIED
>
<!ELEMENT item ANY>
<!ATTLIST item
  chance CDATA #IMPLIED
  id CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
>
<!ELEMENT layout ANY>
<!ATTLIST layout
  class CDATA #IMPLIED
>
<!ELEMENT level ANY>
<!ATTLIST level
  fame CDATA #IMPLIED
  icon CDATA #IMPLIED
  id CDATA #IMPLIED
  ip CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  name CDATA #IMPLIED
  need CDATA #IMPLIED
  value CDATA #IMPLIED
>
<!ELEMENT levels ANY>
<!ATTLIST levels
  max CDATA #IMPLIED
  min CDATA #IMPLIED
>
<!ELEMENT list ANY>
<!ATTLIST list
  noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT logger ANY>
<!ATTLIST logger
  additivity CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT mask ANY>
<!ATTLIST mask
  ip CDATA #IMPLIED
  mask CDATA #IMPLIED
>
<!ELEMENT message ANY>
<!ATTLIST message
  type CDATA #IMPLIED
>
<!ELEMENT messages ANY>
<!ELEMENT minChatMessages ANY>
<!ATTLIST minChatMessages
  all CDATA #IMPLIED
  clan CDATA #IMPLIED
  ip CDATA #IMPLIED
  party CDATA #IMPLIED
  pm CDATA #IMPLIED
  shout CDATA #IMPLIED
  trade CDATA #IMPLIED
>
<!ELEMENT nameColor ANY>
<!ATTLIST nameColor
  color CDATA #IMPLIED
  enable CDATA #IMPLIED
>
<!ELEMENT param ANY>
<!ATTLIST param
  name CDATA #IMPLIED
  val CDATA #IMPLIED
  value CDATA #IMPLIED
>
<!ELEMENT params ANY>
<!ELEMENT quest ANY>
<!ATTLIST quest
  name CDATA #IMPLIED
>
<!ELEMENT reward ANY>
<!ATTLIST reward
  count CDATA #IMPLIED
  id CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT rewards ANY>
<!ATTLIST rewards
  protectReward CDATA #IMPLIED
>
<!ELEMENT root ANY>
<!ELEMENT voting ANY>
<!ATTLIST voting
  command CDATA #IMPLIED
  interval CDATA #IMPLIED
>
<!ELEMENT configuration ANY>
<!ATTLIST configuration
  debug CDATA #IMPLIED
>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/VoteReward.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "config.dtd">
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="VotingReward.xsd">
	<config enableVoteReward="False" />
	<api zone="Hopzone" id="0" key="" /> <!-- #HOPZONE# 12 hours -->
	<api zone="Topzone" id="0" key="" /> <!-- #TOPZONE# 12 hours -->
	<voting command="getreward" interval="12hours" />
	<nameColor enable="false" color="FFFFFF" /> <!-- Color picker: http://www.lineage2.es/misc/l2-user_name_color.php -->
	<messages>
		<message type="ON_SUCCESS">Thank you for voting! Here is small reward from us!</message>
		<message type="ON_NOT_VOTED">You haven't voted yet in %zoneName%!</message>
		<message type="ON_REUSE">You can vote again after: %hours% hours, %mins% minutes and %secs% seconds!</message>
	</messages>
	<rewards>
		<!-- 1st group chance to enter 100% -->
		<group chance="100">
			<!-- The sum of chance inside the group must be always 100% so it always selects at least one item from it! -->
			<!-- Only one item will be selected from a group -->
			<item id="17031" min="1" max="1" chance="100" /> <!-- Vote Box -->
			<item id="6673" min="1" max="4" chance="100" /> <!-- Festival Adena -->
		</group>
		<group chance="60">
			<!-- Elemental Stones -->
			<item id="9546" min="4" max="7" chance="26.66" /> <!-- Fire Stone -->
			<item id="9547" min="4" max="7" chance="26.66" /> <!-- Water Stone -->
			<item id="9548" min="4" max="7" chance="26.66" /> <!-- Earth Stone -->
			<item id="9549" min="4" max="7" chance="26.66" /> <!-- Wind Stone -->
			<item id="9550" min="4" max="7" chance="26.66" /> <!-- Dark Stone -->
			<item id="9551" min="4" max="7" chance="26.66" /> <!-- Holy Stone -->
		</group>
		<group chance="60">
			<!-- Elemental Crystals -->
			<item id="9552" min="1" max="3" chance="16.66" /> <!-- Fire Crystal -->
			<item id="9553" min="1" max="3" chance="16.66" /> <!-- Water Crystal -->
			<item id="9554" min="1" max="3" chance="16.66" /> <!-- Earth Crystal -->
			<item id="9555" min="1" max="3" chance="16.66" /> <!-- Wind Crystal -->
			<item id="9556" min="1" max="3" chance="16.66" /> <!-- Dark Crystal -->
			<item id="9557" min="1" max="3" chance="16.66" /> <!-- Holy Crystal -->
		</group>
		<group chance="50">
			<!-- Enchants -->
			<item id="959" min="1" max="3" chance="45" /> <!-- Scroll: Enchant Weapon (S-Grade) -->
			<item id="960" min="1" max="3" chance="45" /> <!-- Scroll: Enchant Armor (S-Grade) -->
			<!-- Blessed Enchants -->
			<item id="6577" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Weapon (S-Grade) -->
			<item id="6578" min="1" max="3" chance="5" /> <!-- Blessed Scroll: Enchant Armor (S-Grade) -->
		</group>
	</rewards>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/GMAccess.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "config.dtd">
<list>

	<char>
		<PlayerID set="268481576"/>
		<IsGM set="true"/>
		<CanUseGMCommand set="true"/>
		<CanAnnounce set="true"/>
		<CanBan set="true"/>
		<CanBanChat set="true"/>
		<CanUnBanChat set="true"/>
		<BanChatDelay set="-1"/>
		<BanChatMaxValue set="-1"/>
		<BanChatCountPerDay set="-1"/>
		<BanChatBonusId set="-1"/>
		<BanChatBonusCount set="-1"/>
		<CanChatPenalty set="true"/>
		<UseGMShop set="true"/>
		<CanDelete set="true"/>
		<CanKick set="true"/>
		<Menu set="true"/>
		<GodMode set="true"/>
		<CanEditCharAll set="true"/>
		<CanEditChar set="true"/>
		<CanEditPledge set="true"/>
		<CanViewChar set="true"/>
		<CanEditNPC set="true"/>
		<CanViewNPC set="true"/>
		<CanTeleport set="true"/>
		<CanRestart set="true"/>
		<MonsterRace set="true"/>
		<Rider set="true"/>
		<FastUnstuck set="true"/>
		<ResurectFixed set="true"/>
		<Door set="true"/>
		<Res set="true"/>
		<PeaceAttack set="true"/>
		<Heal set="true"/>
		<Unblock set="true"/>
		<CanChangeClass set="true"/>
		<BlockInventory set="false"/>
		<CanGmEdit set="true"/>
		<IsEventGm set="true"/>
		<CanReload set="true"/>
		<CanRename set="true"/>
		<CanJail set="true"/>
		<CanPolymorph set="true"/>
		<UseInventory set="true"/>
		<UseTrade set="true"/>
		<CanAttack set="true"/>
		<CanEvaluate set="true"/>
		<CanJoinParty set="true"/>
		<CanJoinClan set="true"/>
		<UseWarehouse set="true"/>
		<UseShop set="true"/>
	</char>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/GMAccess.d/marshal.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "config.dtd">
<list>
	<char>
		<PlayerID set="-1"/>
		<IsGM set="true"/>
		<CanTeleport set="true"/>
		<GodMode set="true"/>
		<CanUseGMCommand set="true"/>
		<CanTeleport set="true"/>
		<FastUnstuck set="true"/>
		<ResurectFixed set="true"/>
		<Door set="true"/>
		<PeaceAttack set="false"/>
		<UseTrade set="false"/>
		<CanAttack set="false"/>
		<CanJoinClan set="false"/>
		<BlockInventory set="true"/>
		<CanViewChar set="false"/>
	</char>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/ehcache.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ehcache SYSTEM "config.dtd">
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ehcache.xsd" updateCheck="false" monitoring="autodetect">

	<diskStore path="java.io.tmpdir" />

	<defaultCache maxElementsInMemory="1000" eternal="false" timeToIdleSeconds="120" timeToLiveSeconds="120" overflowToDisk="true" diskPersistent="false" diskExpiryThreadIntervalSeconds="120" />

	<!-- DropInfoCache -->
	<cache name="DropInfoCache" maxElementsInMemory="30000" eternal="false" overflowToDisk="false" timeToLiveSeconds="3600" timeToIdleSeconds="600" />

	<!-- HtmCache -->
	<cache name="premium.gameserver.data.htm.HtmCache.RUSSIAN" eternal="true" memoryStoreEvictionPolicy="LRU" maxElementsInMemory="100000" overflowToDisk="false"/>
	<cache name="premium.gameserver.data.htm.HtmCache.ENGLISH" eternal="true" memoryStoreEvictionPolicy="LRU" maxElementsInMemory="100000" overflowToDisk="false"/>

	<!-- ItemInfoCache -->
	<cache name="premium.gameserver.cache.ItemInfoCache" maxElementsInMemory="10000" eternal="false" overflowToDisk="false" timeToLiveSeconds="3600" timeToIdleSeconds="600" />

	<cache name="premium.gameserver.model.items.ItemInstance" maxElementsInMemory="200000" eternal="false" timeToIdleSeconds="1800" memoryStoreEvictionPolicy="LRU" timeToLiveSeconds="3600" overflowToDisk="false" statistics="true" />

	<cache name="premium.gameserver.model.mail.Mail" maxElementsInMemory="100000" eternal="false" timeToIdleSeconds="3600" memoryStoreEvictionPolicy="LRU" timeToLiveSeconds="28800" overflowToDisk="false" statistics="true" />

</ehcache>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/GMAccess.d/minimal_event_manager.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "config.dtd">
<list>
	<char>
		<PlayerID set="-1"/>
		<IsGM set="true"/>
		<CanUseGMCommand set="true"/>
		<CanAnnounce set="true"/>
		<CanBan set="true"/>
		<CanBanChat set="true"/>
		<CanUnBanChat set="true"/>
		<BanChatDelay set="-1"/>
		<BanChatMaxValue set="-1"/>
		<BanChatCountPerDay set="-1"/>
		<BanChatBonusId set="-1"/>
		<BanChatBonusCount set="-1"/>
		<CanChatPenalty set="true"/>
		<UseGMShop set="true"/>
		<CanDelete set="true"/>
		<CanKick set="true"/>
		<Menu set="true"/>
		<GodMode set="true"/>
		<CanEditCharAll set="false"/>
		<CanEditChar set="true"/>
		<CanEditPledge set="false"/>
		<CanViewChar set="true"/>
		<CanEditNPC set="false"/>
		<CanViewNPC set="true"/>
		<CanTeleport set="true"/>
		<CanRestart set="true"/>
		<MonsterRace set="true"/>
		<Rider set="true"/>
		<FastUnstuck set="true"/>
		<ResurectFixed set="true"/>
		<Door set="true"/>
		<Res set="true"/>
		<PeaceAttack set="true"/>
		<Heal set="true"/>
		<Unblock set="true"/>
		<CanChangeClass set="true"/>
		<BlockInventory set="false"/>
		<CanGmEdit set="true"/>
		<IsEventGm set="true"/>
		<CanReload set="false"/>
		<CanRename set="true"/>
		<CanJail set="true"/>
		<CanPolymorph set="true"/>
		<UseInventory set="true"/>
		<UseTrade set="true"/>
		<CanAttack set="true"/>
		<CanEvaluate set="true"/>
		<CanJoinParty set="true"/>
		<CanJoinClan set="true"/>
		<UseWarehouse set="true"/>
		<UseShop set="true"/>
		
		<!-- Only this commands will be available for this GM -->
		<AllowedCommands set="gmspeed;kill;res;heal;setteam;autorecall;teleport;add_mail;remove_mail;cleanse;resetreuse;cancel;para;unpara;remove_coooldown;ip;kick;jail" />
	</char>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/GMAccess.d/event_manager.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "config.dtd">
<list>
	<char>
		<PlayerID set="268597012"/>
		<IsGM set="true"/>
		<CanUseGMCommand set="true"/>
		<CanAnnounce set="true"/>
		<CanBan set="false"/>
		<CanBanChat set="true"/>
		<CanUnBanChat set="true"/>
		<BanChatDelay set="-1"/>
		<BanChatMaxValue set="-1"/>
		<BanChatCountPerDay set="-1"/>
		<BanChatBonusId set="-1"/>
		<BanChatBonusCount set="-1"/>
		<CanChatPenalty set="true"/>
		<UseGMShop set="false"/>
		<CanDelete set="false"/>
		<CanKick set="true"/>
		<Menu set="true"/>
		<GodMode set="true"/>
		<CanEditCharAll set="false"/>
		<CanEditChar set="false"/>
		<CanEditPledge set="false"/>
		<CanViewChar set="true"/>
		<CanEditNPC set="false"/>
		<CanViewNPC set="true"/>
		<CanTeleport set="true"/>
		<CanRestart set="false"/>
		<MonsterRace set="true"/>
		<Rider set="true"/>
		<FastUnstuck set="true"/>
		<ResurectFixed set="true"/>
		<Door set="false"/>
		<Res set="true"/>
		<PeaceAttack set="false"/>
		<Heal set="true"/>
		<Unblock set="true"/>
		<CanChangeClass set="false"/>
		<BlockInventory set="false"/>
		<CanGmEdit set="false"/>
		<IsEventGm set="true"/>
		<CanReload set="false"/>
		<CanRename set="false"/>
		<CanJail set="true"/>
		<CanPolymorph set="true"/>
		<UseInventory set="true"/>
		<UseTrade set="true"/>
		<CanAttack set="true"/>
		<CanEvaluate set="true"/>
		<CanJoinParty set="true"/>
		<CanJoinClan set="true"/>
		<UseWarehouse set="true"/>
		<UseShop set="true"/>
	</char>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/config/mod/DailyQuests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "config.dtd">
<list xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance" ns0:noNamespaceSchemaLocation="DailyQuests.xsd">
	<quest name="ClassSpecificPvPDailyQuest">
		<display name="Quest de PvP com Classe Especifica" description="Voce deve matar players (Classe Especifica)" enabled="false" />
		<levels min="80" max="86" />
		<rewards>
			<category chance="100">
				<item id="6622" min="1" max="5" chance="35" /> <!-- Giant's Codex -->
				<item id="9627" min="1" max="3" chance="35" /> <!-- Giant's Codex - Mastery -->
				<item id="959" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Weapon (S-Grade) -->
				<item id="960" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Armor (S-Grade) -->
				<item id="6577" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Weapon (S-Grade) -->
				<item id="6578" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Armor (S-Grade) -->
			</category>
		</rewards>
		<classes>
			<class id="88" name="Duelist" min="2" max="5" />
			<class id="89" name="Dreadnought" min="1" max="3" />
			<class id="90" name="Phoenix Knight" min="3" max="5" />
			<class id="91" name="Hell Knight" min="2" max="4" />
			<class id="93" name="Adventurer" min="1" max="3" />
			<class id="94" name="Archmage" min="1" max="2" />
			<class id="95" name="Soultaker" min="3" max="5" />
			<class id="97" name="Cardinal" min="3" max="5" />
			<class id="99" name="Eva's Templar" min="3" max="5" />
			<class id="101" name="Wind Rider" min="3" max="5" />
			<class id="103" name="Mystic Muse" min="2" max="4" />
			<class id="106" name="Shillien Templar" min="3" max="5" />
			<class id="108" name="Ghost Hunter" min="3" max="5" />
			<class id="110" name="Storm Screamer" min="3" max="5" />
			<class id="113" name="Titan" min="2" max="5" />
			<class id="114" name="Grand Khavatari" min="2" max="4" />
			<class id="115" name="Dominator" min="3" max="5" />
			<class id="117" name="Fortune Seeker" min="3" max="6" />
			<class id="131" name="Doombringer" min="1" max="2" />
			<class id="132" name="Male Soul Hound" min="2" max="4" />
			<class id="133" name="Female Soul Hound" min="2" max="4" />
			<class id="134" name="Trickster" min="1" max="2" />
		</classes>
		<params>
			<!-- Formula: KillStaticCount + (KillAddonCount * getRandom(KillAddonMinCount, KillAddonMaxCount) -->
			<param name="KillStaticCount" val="5" />
			<param name="KillAddonCount" val="1" />
			<param name="KillAddonMinCount" val="1" />
			<param name="KillAddonMaxCount" val="5" />
		</params>
	</quest>
	<quest name="FishingDailyQuest">
		<display name="Quest de Pescaria" description="Voce deve pegar alguns peixes" enabled="true" />
		<levels min="40" max="86" />
		<rewards protectReward="false">
			<category chance="100">
				<item id="7609" min="50" max="150" chance="30" /> <!-- Proof Of Catching A Fish -->
				<item id="7586" min="20" max="60" chance="30" /> <!-- Sweet Fluid -->
				<item id="13258" min="5" max="10" chance="10" /> <!-- Gran Kain's Blessed Scroll of Escape -->
				<item id="13259" min="5" max="10" chance="10" /> <!-- Gran Kain's Blessed Scroll of Resurrection -->
				<item id="6540" min="20" max="50" chance="10" /> <!-- Fishing Shot (S-Grade) -->
				<item id="10178" min="1" max="2" chance="5" /> <!-- Sweet Fruit Cocktail -->
				<item id="10179" min="1" max="2" chance="5" /> <!-- Fresh Fruit Cocktail -->
			</category>
		</rewards>
		<params>
			<!-- Formula: KillStaticCount + (KillsAddonCount * getRandom(KillsAddonMinCount, KillsAddonMaxCount) -->
			<param name="KillStaticCount" val="20" />
			<param name="KillAddonCount" val="10" />
			<param name="KillAddonMinCount" val="1" />
			<param name="KillAddonMaxCount" val="5" />
		</params>
	</quest>
	<quest name="GeneralPvPDailyQuest">
		<display name="Quest de PvP Geral" description="Voce deve matar qualquer player" enabled="true" />
		<levels min="80" max="86" />
		<rewards>
			<category chance="100">
				<item id="6622" min="1" max="5" chance="35" /> <!-- Giant's Codex -->
				<item id="9627" min="1" max="3" chance="35" /> <!-- Giant's Codex - Mastery -->
				<item id="959" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Weapon (S-Grade) -->
				<item id="960" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Armor (S-Grade) -->
				<item id="6577" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Weapon (S-Grade) -->
				<item id="6578" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Armor (S-Grade) -->
			</category>
			<category chance="100">
				<item id="-300" min="1000" max="2000" chance="50" /> <!-- Fame -->
				<item id="-200" min="200" max="600" chance="50" /> <!-- Clan Reputation -->
			</category>
		</rewards>
		<params>
			<!-- Formula: KillStaticCount + (KillsAddonCount * getRandom(KillsAddonMinCount, KillsAddonMaxCount) -->
			<param name="KillStaticCount" val="40" />
			<param name="KillAddonCount" val="10" />
			<param name="KillAddonMinCount" val="1" />
			<param name="KillAddonMaxCount" val="3" />
		</params>
	</quest>
	<quest name="PKHunterDailyQuest">
		<display name="Caçador de PK" description="Voce deve matar de 5-10 Players PK" enabled="true" />
		<levels min="70" max="86" />
		<rewards>
			<category chance="100">
				<item id="6622" min="1" max="5" chance="35" /> <!-- Giant's Codex -->
				<item id="9627" min="1" max="3" chance="35" /> <!-- Giant's Codex - Mastery -->
				<item id="959" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Weapon (S-Grade) -->
				<item id="960" min="1" max="3" chance="10" /> <!-- Scroll: Enchant Armor (S-Grade) -->
				<item id="6577" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Weapon (S-Grade) -->
				<item id="6578" min="1" max="1" chance="5" /> <!-- Blessed Scroll: Enchant Armor (S-Grade) -->
			</category>
			<category chance="100">
				<item id="9552" min="1" max="3" chance="16.66" /> <!-- Fire Crystal -->
				<item id="9553" min="1" max="3" chance="16.66" /> <!-- Water Crystal -->
				<item id="9554" min="1" max="3" chance="16.66" /> <!-- Earth Crystal -->
				<item id="9555" min="1" max="3" chance="16.66" /> <!-- Wind Crystal -->
				<item id="9556" min="1" max="3" chance="16.66" /> <!-- Dark Crystal -->
				<item id="9557" min="1" max="3" chance="16.66" /> <!-- Holy Crystal -->
			</category>
		</rewards>
		<params>
			<!-- Formula: KillStaticCount + (KillAddonCount * getRandom(KillAddonMinCount, KillAddonMaxCount) -->
			<param name="KillStaticCount" val="5" />
			<param name="KillAddonCount" val="1" />
			<param name="KillAddonMinCount" val="0" />
			<param name="KillAddonMaxCount" val="5" />
		</params>
	</quest>
	<quest name="EnchantingDailyQuest">
		<display name="Quest de Enchant" description="Você deve Enchantar de 5-10 Items Grade-S" enabled="true" />
		<levels min="76" max="86" />
		<rewards>
			<category chance="100">
				<item id="959" min="5" max="10" chance="50" /> <!-- Scroll: Enchant Weapon (S-Grade) -->
				<item id="960" min="5" max="15" chance="50" /> <!-- Scroll: Enchant Armor (S-Grade) -->
			</category>
			<category chance="100">
				<item id="6577" min="1" max="2" chance="45" /> <!-- Blessed Scroll: Enchant Weapon (S-Grade) -->
				<item id="6578" min="1" max="3" chance="45" /> <!-- Blessed Scroll: Enchant Armor (S-Grade) -->
			</category>
		</rewards>
		<params>
			<!-- Formula: KillStaticCount + (KillAddonCount * getRandom(KillAddonMinCount, KillAddonMaxCount) -->
			<param name="KillStaticCount" val="5" />
			<param name="KillAddonCount" val="1" />
			<param name="KillAddonMinCount" val="0" />
			<param name="KillAddonMaxCount" val="5" />

			<param name="ArmorMinEnchant" val="5" />
			<param name="WeaponMinEnchant" val="7" />
		</params>
	</quest>
</list>
