=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/skills.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (skill)*>
<!ELEMENT skill (table|set|for|cond|enchant1|enchant2|enchant3|enchant4|enchant5|enchant6|enchant7|enchant8|triggers)*>
<!ATTLIST skill
	id CDATA #REQUIRED
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT table (#PCDATA)>
<!ATTLIST table
	name CDATA #REQUIRED>
<!ELEMENT set EMPTY>
<!ATTLIST set
	name CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT enchant1 (table|set)*>
<!ATTLIST enchant1
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant2 (table|set)*>
<!ATTLIST enchant2
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant3 (table|set)*>
<!ATTLIST enchant3
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant4 (table|set)*>
<!ATTLIST enchant4
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant5 (table|set)*>
<!ATTLIST enchant5
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant6 (table|set)*>
<!ATTLIST enchant6
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant7 (table|set)*>
<!ATTLIST enchant7
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT enchant8 (table|set)*>
<!ATTLIST enchant8
	levels CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT for (add|sub|mul|div|set|enchant|effect|triggers)*>
<!ELEMENT add EMPTY>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	val CDATA #IMPLIED>
<!ELEMENT sub EMPTY>
<!ATTLIST sub
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	val CDATA #IMPLIED>
<!ELEMENT mul EMPTY>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	val CDATA #IMPLIED>
<!ELEMENT div EMPTY>
<!ATTLIST div
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	val CDATA #IMPLIED>
<!ELEMENT bas EMPTY>
<!ATTLIST bas
	stat CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT enchant EMPTY>
<!ATTLIST enchant
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT effect (add|sub|mul|div|set|def|and|or|not|player|target|has|using|game|zone|triggers)*>
<!ATTLIST effect
	name CDATA #REQUIRED
	val CDATA #IMPLIED
	count CDATA #IMPLIED
	time CDATA #IMPLIED
	abnormal CDATA #IMPLIED
	stackType CDATA #IMPLIED
	stackType2 CDATA #IMPLIED
	stackOrder CDATA #IMPLIED
	applyOnCaster CDATA #IMPLIED
	applyOnSummon CDATA #IMPLIED
	displayId CDATA #IMPLIED
	displayLevel CDATA #IMPLIED
	chance CDATA #IMPLIED
	cancelOnAction CDATA #IMPLIED
	isOffensive CDATA #IMPLIED
	isReflectable CDATA #IMPLIED>
<!ELEMENT def EMPTY>
<!ATTLIST def
	name CDATA #REQUIRED
	val CDATA #REQUIRED>
<!ELEMENT cond (and|or|not|player|target|has|using|game|zone)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED
	addName CDATA #IMPLIED>
<!ELEMENT and (and|or|not|player|target|has|using|game|zone)*>
<!ELEMENT or (and|or|not|player|target|has|using|game|zone)*>
<!ELEMENT not (and|or|not|player|target|has|using|game|zone)*>
<!ELEMENT player EMPTY>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	classId CDATA #IMPLIED
	minLevel CDATA #IMPLIED
	maxLevel CDATA #IMPLIED
	maxPK CDATA #IMPLIED
	percentHP CDATA #IMPLIED
	percentMP CDATA #IMPLIED
	percentCP CDATA #IMPLIED
	agathion CDATA #IMPLIED
	cubic CDATA #IMPLIED
	fightClub CDATA #IMPLIED
	hasBuff CDATA #IMPLIED
	hasBuffId CDATA #IMPLIED
	riding CDATA #IMPLIED
	summonSiegeGolem CDATA #IMPLIED
	resting CDATA #IMPLIED
	moving CDATA #IMPLIED
	running CDATA #IMPLIED
	standing CDATA #IMPLIED
	flying CDATA #IMPLIED
	flyingTransform CDATA #IMPLIED
	behind CDATA #IMPLIED
	front CDATA #IMPLIED
	side CDATA #IMPLIED
	chaotic CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	minDamage CDATA #IMPLIED
	maxDamage CDATA #IMPLIED>
<!ELEMENT target EMPTY>
<!ATTLIST target
	aggro CDATA #IMPLIED
	castle_door CDATA #IMPLIED
	clan CDATA #IMPLIED
	direction CDATA #IMPLIED
	forbiddenClass CDATA #IMPLIED
	hasBuff CDATA #IMPLIED
	hasBuffId CDATA #IMPLIED
	hasForbiddenSkill CDATA #IMPLIED
	mob CDATA #IMPLIED
	mobId CDATA #IMPLIED
	npc_class CDATA #IMPLIED
	percentHP CDATA #IMPLIED
	percentMP CDATA #IMPLIED
	percentCP CDATA #IMPLIED
	playable CDATA #IMPLIED
	player CDATA #IMPLIED
	playerRace CDATA #IMPLIED
	race CDATA #IMPLIED
	summon CDATA #IMPLIED
	active_skill_id CDATA #IMPLIED>
<!ELEMENT has EMPTY>
<!ATTLIST has
	skill CDATA #IMPLIED
	skillId CDATA #IMPLIED>
<!ELEMENT using EMPTY>
<!ATTLIST using
	kind CDATA #IMPLIED
	armor CDATA #IMPLIED
	skill CDATA #IMPLIED
	slotitem CDATA #IMPLIED>
<!ELEMENT game EMPTY>
<!ATTLIST game
	night CDATA #IMPLIED>
<!ELEMENT zone EMPTY>
<!ATTLIST zone
	type CDATA #REQUIRED>
<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (and|or|not|player|target|has|using|game|zone)*>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/90000-90099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="90001" levels="2" name="Mana potion">
		<table name="#power">1000 1300 </table>
		<table name="#val">1 0</table>
		<table name="#val2">728 37001</table>
		<set name="icon" val="" />
		<set name="displayId" val="2005" />
		<set name="itemConsumeId" val="#val2" />
		<set name="itemConsumeCount" val="#val" />
		<set name="isHandler" val="true" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="MANAHEAL" />
		<set name="power" val="#power" />
		<set name="operateType" val="OP_ACTIVE" />
		<set name="altUse" val="true" />
	</skill>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/24000-24100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="24001" levels="1" name="Support Power Cardinal">
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="mAtkSpd" val="1.10" />
			<mul order="0x30" stat="paralyzeResist" val="1.10" />
		</for>
	</skill>
	<skill id="24002" levels="1" name="Support Power Hierophant" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="maxMp" val="1.10" />
			<mul order="0x30" stat="paralyzeResist" val="1.10" />
		</for>
	</skill>
	<skill id="24003" levels="1" name="Support Power Sword Muse" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<mul order="0x30" stat="pAtkSpd" val="1.10" />
			<mul order="0x30" stat="maxHp" val="1.10" />
			<mul order="0x30" stat="rootResist" val="1.10" />
		</for>
	</skill>
	<skill id="24004" levels="1" name="Support Power Eva Saint" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="regMp" val="1.10" />
			<mul order="0x30" stat="rootResist" val="1.10" />
		</for>
	</skill>
	<skill id="24005" levels="1" name="Support Power Spectral Dancer" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="maxHp" val="1.10" />
			<mul order="0x30" stat="rootResist" val="1.10" />
		</for>
	</skill>
	<skill id="24006" levels="1" name="Support Power Shillien Saint" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="maxMp" val="1.10" />
			<mul order="0x30" stat="stunResist" val="1.10" />
		</for>
	</skill>
	<skill id="24007" levels="1" name="Support Power Dominator" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="maxMp" val="1.10" />
			<mul order="0x30" stat="stunResist" val="1.10" />
		</for>
	</skill>
	<skill id="24008" levels="1" name="Support Power Doomcryer" >
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<add order="0x40" stat="runSpd" val="35" />
			<mul order="0x30" stat="maxMp" val="1.10" />
			<mul order="0x30" stat="paralyzeResist" val="1.10" />
		</for>
	</skill>
	<skill id="24009" levels="3" name="Luckpy Power" >
		<table name="#pDef">0.06 0.5 1</table>
		<table name="#mDef">0.06 0.5 1</table>
		<set name="icon" val="icon.skill3123" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<mul order="0x30" stat="pDef" val="#pDef" />
			<mul order="0x30" stat="mDef" val="#mDef" />
		</for>
	</skill>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/22400-22499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="22400" levels="1" name="Transformation Scroll - Zaken" >
		<set name="magicType" val="SPECIAL" />
		<set name="icon" val="icon.skilltransform1" />
		<set name="reuseDelay" val="7200000" />
		<set name="itemConsumeId" val="17140" />
		<set name="itemConsumeCount" val="1" />
		<set name="isHandler" val="true" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="TRANSFORMATION" />
		<set name="addSkills" val="717;4;718;4;715;4;716;4;719;1;619;1" />
		<set name="npcId" val="13099" />
		<set name="operateType" val="OP_ACTIVE" />
		<for>
			<effect count="1" name="Transformation" time="1800" val="305">
				<set order="0x40" stat="STR" val="48" />
				<set order="0x40" stat="DEX" val="30" />
				<set order="0x40" stat="CON" val="52" />
				<set order="0x40" stat="INT" val="45" />
				<set order="0x40" stat="WIT" val="20" />
				<set order="0x40" stat="MEN" val="45" />
			</effect>
		</for>
	</skill>
	<skill id="22401" levels="1" name="Transformation Scroll - Ranku" >
		<set name="magicType" val="SPECIAL" />
		<set name="icon" val="icon.skilltransform1" />
		<set name="hitTime" val="500" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="TRANSFORMATION" />
		<set name="addSkills" val="731;1;732;1;619;1;5491;1" />
		<set name="npcId" val="13103" />
		<set name="operateType" val="OP_ACTIVE" />
		<set name="isHandler" val="true" />
		<set name="itemConsumeId" val="21189" />
		<set name="itemConsumeCount" val="1" />
		<cond msgId="1509">
			<not>
				<player olympiad="true" />
			</not>
		</cond>
		<for>
			<effect count="1" name="Transformation" time="1800" val="309">
				<set order="0x40" stat="STR" val="43" />
				<set order="0x40" stat="DEX" val="30" />
				<set order="0x40" stat="CON" val="47" />
				<set order="0x40" stat="INT" val="46" />
				<set order="0x40" stat="WIT" val="20" />
				<set order="0x40" stat="MEN" val="42" />
			</effect>
		</for>
	</skill>
	<skill id="22402" levels="1" name="Juju Agathion's Gift" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22403" levels="1" name="Extra Entrance Pass - Kamaloka (Hall of the Abyss)" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22404" levels="1" name="Pathfinder's Reward" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22405" levels="1" name="S84 Top-Grade Weapon Box" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22406" levels="1" name="Ellegia Armor Box" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22407" levels="1" name="PC Cafe Energy" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.etc_pccafe_point_i00" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22408" levels="1" name="Enchantment Tool Box" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0000" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="22409" levels="2" name="Rune of Fate" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="br_cashtex.item.br_cash_rune_of_feather_i00" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/20000-20099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="20000" levels="1" name="Treasure Hunter Search" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="BranchSys2.icon.br_s_search_treasure1_i00" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20001" levels="1" name="Treasure Hunter Hammer Punch" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="BranchSys2.icon.br_s_hammerpunch_treasure1_i001" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20002" levels="1" name="Dragon Kick" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill_transform_s_attack" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20003" levels="1" name="Dragon Slash" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill_transform_s_attack" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20004" levels="1" name="Dragon Dash" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill_transform_buff" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20005" levels="1" name="Dragon Aura" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill_transform_buff" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="20006" levels="1" name="Soul Roar" >
		<set name="icon" val="BranchSys2.icon.skill20006" />
		<table name="#effectPoint">611</table>
		<table name="#magicLevel">62</table>
		<set name="reuseDelay" val="240000" />
		<set name="hitTime" val="1500" />
		<set name="hitCancelTime" val="350" />
		<set name="mpConsume1" val="58" />
		<set name="mpConsume2" val="14" />
		<set name="effectPoint" val="#effectPoint" />
		<set name="magicLevel" val="#magicLevel" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_ACTIVE" />
		<for>
			<effect count="1" name="Buff" time="600" val="0">
				<mul order="0x30" stat="maxHp" val="1.15" />
				<mul order="0x30" stat="maxCp" val="1.15" />
			</effect>
			<effect count="1" name="HealPercent" time="0" val="15"/>
			<effect count="1" name="HealCPPercent" time="0" val="15"/>
		</for>
	</skill>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/14100-14199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="14156" levels="1" name="Snake" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0006" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14157" levels="1" name="Long Snake" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0006" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14158" levels="1" name="Crawler Spear" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0006" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14164" levels="1" name="Akain Jet" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill1275" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14165" levels="1" name="Akain Burst" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill1275" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14167" levels="1" name="Black Powder" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill0006" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
	<skill id="14168" levels="1" name="Throw Granade" >
		<!--  Automatically generated from The High Five: Part 4.5 client files.
		  Description: none
		  Target is set to TARGET_NONE, skillType  to NOTDONE for server compatability.
		  created 07-7-2011  19:19
		-->
		<set name="icon" val="icon.skill1275" />
		<set name="target" val="TARGET_NONE" />
		<set name="skillType" val="NOTDONE" />
		<set name="operateType" val="OP_ACTIVE" />
	</skill>
</list>

=== jacksonfelipe/L2JPremium-High-Five-/world/data/stats/skills/Conflict Skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
	<skill id="91000" levels="1" name="Vote Reward Rune" >
		<!--
		      Description: Gives 25% Exp Bonus and 25% Adena Drop Bonus. Also 1% Patk, Matk, Pdef, Mdef
		-->
		<set name="icon" val="br_cashtex.skill.br_cash_rune_of_exp_buff_1" />
		<set name="magicLevel" val="1" />
		<set name="target" val="TARGET_SELF" />
		<set name="skillType" val="BUFF" />
		<set name="operateType" val="OP_PASSIVE" />
		<for>
			<add order="0x40" stat="ExpMultiplier" val="0.50" />
			<add order="0x40" stat="AdenaMultiplier" val="0.30" />
			<mul order="0x30" stat="pAtk" val="1.03" />
			<mul order="0x30" stat="mAtk" val="1.03" />
			<mul order="0x30" stat="pDef" val="1.03" />
			<mul order="0x30" stat="mDef" val="1.03" />
		</for>
	</skill>
</list>
